### ISSUE TITLE
example values for imap2_open and outlook.office365.com

### ISSUE THREAD

**Issue by mpoetzsch** [javanile/php-imap2#23]
I try to use your lib for connecting to outlook.office365.com with imap2_open(...) but couldnt connect. Do you have managed it, and can you add some examples to docu or here?

**Comment by francescobianco** [comment]
This is the minimal example for outlook

```php
<?php
$mailbox = '{outlook.office365.com:993/imap/ssl}';
$username = 'sam.sapiol@contoso.onmicrosoft.com';
$accessToken = '...';

$imap = imap2_open($mailbox, $username, $accessToken, OP_XOAUTH2);
```

the `$accessToken` is the one you get with a call like this <https://github.com/javanile/php-imap-outlook/blob/main/public/index.php#L25>

**Comment by mpoetzsch** [comment]
Thank you! Really! I will try it :D
