### ISSUE TITLE
PHP Imap 2 outlook 

### ISSUE THREAD

**Issue by albertopitti** [javanile/php-imap2#44]
I'm trying to authenticate to outlook, the azure application is configured well, I tested it with the powershell script mentioned here  [http://wiki.canfigure.net/en/guides/exchange-oauth2](http://wiki.canfigure.net/en/guides/exchange-oauth2), but I receive the message: 
` Can not authenticate to IMAP server: A0001 NO AUTHENTICATE failed.` 
I obtain the token with [https://github.com/TheNetworg/oauth2-azure](https://github.com/TheNetworg/oauth2-azure) and it works fine and then try with 
`imap2_open('{outlook.office365.com:993/imap/ssl}', 'name@domain.com', $token, OP_XOAUTH2)`
got me that error

**Comment by gabriel-tandil** [comment]
if it is a generic domain account try adding **MAILBOX** after _.../ssl}_

**Comment by albertopitti** [comment]
I found the issue, it was on the library to get the token, it uses an old endpoint and still gives me a token
