### ISSUE TITLE
MS Outlook connectivity

### ISSUE THREAD

**Issue by cjwnz** [javanile/php-imap2#8]
Hi there

I'm having some issues connecting to Outlook.
I can successfully obtain the Access Token using scope `https://outlook.office.com/.default`
I'm then preparing the Access Token as follows:

`base64_encode("user=".$username."\x01auth=Bearer $access_token\x01\x01");`

But the call to imap2_open to `{outlook.office365.com:993/imap/ssl}INBOX` fails with:

`Can not authenticate to IMAP server: A0001 NO AUTHENTICATE failed.`

Anything obvious I'm doing wrong?
Any examples connecting to Outlook 365 appreciated!

**Comment by cjwnz** [comment]
I have now resolved this issue. 
But I think if you want people to use this library you'd better start answering some of the issues ;-)
Thanks.

**Comment by rmaxe** [comment]
Hi @cjwnz,

I've got the exact same issue, would you please share your solution?
Thanks!

**Comment by cjwnz** [comment]
Hi rmaxe - make sure you follow closely all the instructions from Microsoft including the command-line powershell commands.
It's not straight forward and we have prepared our own instructions/tips here:

http://wiki.canfigure.net/en/guides/exchange-oauth2

**Comment by francescobianco** [comment]
## IMPORTANT!

> You do not need encode the token on base64, this library already do it by itself

Avoid code like this (DO NOT DO THIS)
```
base64_encode("user=".$username."\x01auth=Bearer $access_token\x01\x01");
```

cc @cjwnz @rmaxe

**Comment by francescobianco** [comment]
# TEST LIVE - Outlook

On this link you can test Microsoft Outlook connectivity <https://php-imap-outlook.herokuapp.com/>

**Comment by Orgoth** [comment]
> # TEST LIVE - Outlook
> On this link you can test Microsoft Outlook connectivity https://php-imap-outlook.herokuapp.com/

Unfortunately, when I try to log in with my Microsoft account using the mentioned link, I only get an error message after I confirm. "....@outlook.com"

```php
$_SESSION['auth'] = array(7) {
  ["error"]=>
  string(13) "invalid_grant"
  ["error_description"]=>
  string(199) "AADSTS9002313: Invalid request. Request is malformed or invalid.
Trace ID: 9fd3edd3-9739-4113-b076-5a2907eaae00
Correlation ID: 640228a9-81e7-4657-8c04-e0672d14dcc0
Timestamp: 2022-10-05 12:13:28Z"
  ["error_codes"]=>
  array(1) {
    [0]=>
    int(9002313)
  }
  ["timestamp"]=>
  string(20) "2022-10-05 12:13:28Z"
  ["trace_id"]=>
  string(36) "9fd3edd3-9739-4113-b076-5a2907eaae00"
  ["correlation_id"]=>
  string(36) "640228a9-81e7-4657-8c04-e0672d14dcc0"
  ["error_uri"]=>
  string(52) "https://login.microsoftonline.com/error?code=9002313"
}
```

With version 0.19 I can connect to my ms-app.

#### Example:
```
$resource = imap2_open(
	$this->getServerString(),
	$username,
	$password,
	$this->options,
	1,
	$this->parameters
);
```

#### ServerString
```
{outlook.office365.com:993/imap/ssl/novalidate-cert}
```
#### Username
```
test@outlook.com
```
#### Password
```
OAuth Token "around 1120 charaters long"
```
#### Options
```
512
```
#### Parameters
```
[]
```

Another hint, you should omit INBOX in the ServerString, because this folder is not always present and then leads to errors.
At Microsoft the folder is called Inbox.
If this is specified as Capslock, you receive the error message that the folder does not exist.

**Comment by darkworks** [comment]
The annoying thing about outlook is that microsfot not offering any of their MSAL lib for php.

**Comment by darkworks** [comment]
> $this->options,
> 	1,
> 	$this->parameters

thanks for the instructions . am getting access token however like my script when i trouble shoot with your powershell script i get same error
` ERROR during authentication A01 NO AUTHENTICATE failed. `

am not able to follow this step
![image](https://user-images.githubusercontent.com/12841788/196604235-a2dd20b1-e963-4588-973f-f746cd8c29aa.png)

i do not have office 365 online in the list as its due to because my email is **xxxxxx@live.com** ??
![image](https://user-images.githubusercontent.com/12841788/196604331-3bb4c9f3-efb7-439f-8dc6-0fb5c7bf8132.png)

so far i have added these permissions 

![image](https://user-images.githubusercontent.com/12841788/196604443-f7f2d79c-9c46-4d56-b5f1-b99c89033922.png)

but unlike my script the power shell also return `ERROR during authentication A01 NO AUTHENTICATE failed.`
![image](https://user-images.githubusercontent.com/12841788/196604507-1293122c-0a68-41b3-acda-8d1c9e6c6e48.png)
my php script 
`can't connect: Can not authenticate to IMAP server: A0001 NO AUTHENTICATE failed.`

**Comment by darkworks** [comment]
> Hi rmaxe - make sure you follow closely all the instructions from Microsoft including the command-line powershell commands. It's not straight forward and we have prepared our own instructions/tips here:
> 
> http://wiki.canfigure.net/en/guides/exchange-oauth2

thanks for the instructions . am getting access token however like my script when i trouble shoot with your powershell script i get same error
` ERROR during authentication A01 NO AUTHENTICATE failed. `

am not able to follow this step
![image](https://user-images.githubusercontent.com/12841788/196604235-a2dd20b1-e963-4588-973f-f746cd8c29aa.png)

i do not have office 365 online in the list as its due to because my email is **xxxxxx@live.com** ??
![image](https://user-images.githubusercontent.com/12841788/196604331-3bb4c9f3-efb7-439f-8dc6-0fb5c7bf8132.png)

so far i have added these permissions 

![image](https://user-images.githubusercontent.com/12841788/196604443-f7f2d79c-9c46-4d56-b5f1-b99c89033922.png)

but unlike my script the power shell also return `ERROR during authentication A01 NO AUTHENTICATE failed.`
![image](https://user-images.githubusercontent.com/12841788/196604507-1293122c-0a68-41b3-acda-8d1c9e6c6e48.png)
my php script 
`can't connect: Can not authenticate to IMAP server: A0001 NO AUTHENTICATE failed.`

**Comment by darkworks** [comment]
> [
>             'applicationId' => '...',
>             'applicationSecret' => '...',
>             'scope' => [
>                 'wl.basic',
>                 'wl.imap',
>                 'wl.emails',
>                 'wl.offline_access',
>                 'https://outlook.office.com/IMAP.AccessAsUser.All',
>                 'https://outlook.office.com/SMTP.Send',
>                 'https://graph.microsoft.com/SMTP.Send',
>                 'https://graph.microsoft.com/IMAP.AccessAsUser.All',
>             ]

hmmmm can u tell how to pass these scopes to imap2_openfunction 
currently i have this 
```php
imap2_open($this->mail_server, $this->email_id, $this->access_token, OP_XOAUTH2 ) or die("can't connect: " . imap2_last_error());
```
thanks

**Comment by Orgoth** [comment]
The Scopes must be transferred when you request the token.
I am using SocialConnect for this.
> https://github.com/SocialConnect/auth

I also tried to set the permissions via the Azure platform, that was possible though.
But when I tried it, it turned out that this did not work.
Only when I passed the appropriate permissions/scopes with the request, the login worked afterwards.

imap2_open sends only the credentials.
If the retrieved token does not have the appropriate permissions, the login fails.

**Comment by darkworks** [comment]
> 'wl.basic',
> 'wl.imap',
> 'wl.emails',
> 'wl.offline_access',
> 'https://outlook.office.com/IMAP.AccessAsUser.All',
> 'https://outlook.office.com/SMTP.Send',
> 'https://graph.microsoft.com/SMTP.Send',
> 'https://graph.microsoft.com/IMAP.AccessAsUser.All',

hmmm changed scopes however same issue. am using : https://github.com/TheNetworg/oauth2-azure

will change to Socialconnet to see if there is lib issue

**Comment by darkworks** [comment]
@Orgoth Ok so this is for log purpose
if you keep getting error : `ERROR during authentication A01 NO AUTHENTICATE failed.`
then make sure use SocialConnect : https://github.com/SocialConnect/auth
avoid using this lib : oauth2-azure https://github.com/TheNetworg/oauth2-azure  its buggy and you will get errors like `ERROR during authentication A01 NO AUTHENTICATE failed.`

**Comment by adamhealthystuff** [comment]
Social Connect
This keeps redirecting me to a "We're unable to complete your request" page. The current social connect microsoft config seems to use the old microsoft apps which was deprecated in 2019?

How did you use Social Connect for azure? The azure-ad they added doesnt work either?

OAuth2-Azure
ERROR during authentication A01 NO AUTHENTICATE failed.

Outlook Example Login
ERROR during authentication A01 NO AUTHENTICATE failed.

**Comment by Orgoth** [comment]
Microsoft is just frustrating.
Private accesses work, but B2B "business connections" unfortunately not at all.
Even Azure Support had to admit defeat.
I am currently waiting for feedback on my ticket and problem. :(

The joke is, after creating an app, Microsoft greets the user with the message that no more features will be added to ADAL and Azure AD Graph after 2020.
Only technical support and that you should switch to MSAL.

https://techcommunity.microsoft.com/t5/microsoft-entra-azure-ad-blog/azure-ad-change-management-simplified/ba-p/2967456

I couldn't really find any clear guidance either.
I, or rather we in the company, will recommend to our customers to look for another service provider.

**Comment by darkworks** [comment]
@Orgoth can you share you Outh issue maybe i can help you out. any error etc you getting.

**Comment by Orgoth** [comment]
@darkworks 

> AADSTS500011: The resource principal named https://graph.microsoft.com/offline_access,https://graph.microsoft.com/Mail.ReadWrite,https://graph.microsoft.com/Mail.Send,https://graph.microsoft.com was not found in the tenant named *******. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.

This is the Problem I have, when trying the OAuth for B2B.
-> https://login.microsoftonline.com/tenant_from_azure_ad/oauth2/v2.0/authorize

For Private-Accounts there is no tenant needed, and the user can simply grant the access.  
-> https://login.live.com/oauth20_authorize.srf

I made a team meeting directly with Microsoft support to solve the problem with their help. "Screenshare"  
Unfortunately, they also did not know why the message still comes despite the correct tenant and rights.

**Comment by darkworks** [comment]
hmmm try with these scopes 

```
	'scopes'    => [
		'offline_access',
		'https://outlook.office365.com/Mail.Read',
		'https://outlook.office365.com/profile',
		'https://outlook.office365.com/IMAP.AccessAsUser.All',
	],
```
there is typo in Azur portal for business emails they show incorrect scopes like 
```
https://graph.microsoft.com/offline_access,https://graph.microsoft.com/Mail.ReadWrite,https://graph.microsoft.com/Mail.Send,https://graph.microsoft.com
```
correct scopes are the one which i mentioned

**Comment by darkworks** [comment]
+ also try with this lib 
https://github.com/TheNetworg/oauth2-azure

`composer require thenetworg/oauth2-azure`

then try something like this

```php
require_once './vendor/autoload.php';

	// init outh client
	$microsoft_outh = new TheNetworg\OAuth2\Client\Provider\Azure([
	'clientId'          => 'your app client id',
	'clientSecret'      => 'app secret id',
	'redirectUri'       => 'redirect url must match with azure portal ',
	'approval_prompt' => 'auto',
	'scopes'    => [
		'offline_access',
		'https://outlook.office365.com/Mail.Read',
		'https://outlook.office365.com/profile',
		'https://outlook.office365.com/IMAP.AccessAsUser.All',
	],
	'defaultEndPointVersion' => '2.0'
	]);
```

**Comment by darkworks** [comment]
+ during app registration must select option 3 like this

![image](https://user-images.githubusercontent.com/12841788/201080146-5cfef016-40b5-4212-b643-05f2aa7000ea.png)

**Comment by Orgoth** [comment]
> hmmm try with these scopes
> 
> ```
> 	'scopes'    => [
> 		'offline_access',
> 		'https://outlook.office365.com/Mail.Read',
> 		'https://outlook.office365.com/profile',
> 		'https://outlook.office365.com/IMAP.AccessAsUser.All',
> 	],
> ```
> 
> there is typo in Azur portal for business emails they show incorrect scopes like
> 
> ```
> https://graph.microsoft.com/offline_access,https://graph.microsoft.com/Mail.ReadWrite,https://graph.microsoft.com/Mail.Send,https://graph.microsoft.com
> ```
> 
> for business emails correct scopes are the one which i mentioned . the scopes which you are using currently will work only for non business emails mean free @LiVe emails


The Scopes you have mentioned, are not available within the Azure AD.  


![Auswahl_322](https://user-images.githubusercontent.com/1035170/201080623-23897856-d9c2-4435-80df-6ae1a4b95d12.png)


I will try the scopes, even if they are not available at all in Azure.  


> * during app registration must select option 3 like this
> 
> ![image](https://user-images.githubusercontent.com/12841788/201080146-5cfef016-40b5-4212-b643-05f2aa7000ea.png)

Yes, this is how I registered the app.  
Also, the Redirection is set.

> * also try with this lib
>   https://github.com/TheNetworg/oauth2-azure
> 
> `composer require thenetworg/oauth2-azure`
> 
> then try something like this
> 
> ```
> require_once './vendor/autoload.php';
> 
> 	// init outh client
> 	$microsoft_outh = new TheNetworg\OAuth2\Client\Provider\Azure([
> 	'clientId'          => 'your app client id',
> 	'clientSecret'      => 'app secret id',
> 	'redirectUri'       => 'redirect url must match with azure portal ',
> 	'approval_prompt' => 'auto',
> 	'scopes'    => [
> 		'offline_access',
> 		'https://outlook.office365.com/Mail.Read',
> 		'https://outlook.office365.com/profile',
> 		'https://outlook.office365.com/IMAP.AccessAsUser.All',
> 	],
> 	'defaultEndPointVersion' => '2.0'
> 	]);
> ```

I need a Lib for Google and Microsoft.  
I don't want to have to install an additional lib for each service provider.  

Thanks already for the efforts.

**Comment by Orgoth** [comment]
@darkworks

> AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope offline_access,https://outlook.office365.com/Mail.Read,https://outlook.office365.com/profile,https://outlook.office365.com/IMAP.AccessAsUser.All is not valid. The scope format is invalid. Scope must be in a valid URI form <https://example/scope> or a valid Guid <guid/scope>.

**Comment by darkworks** [comment]
hmmmm which outh lib you are using ? social connect or the one which i shared

**Comment by Orgoth** [comment]
> @Orgoth Ok so this is for log purpose if you keep getting error : `ERROR during authentication A01 NO AUTHENTICATE failed.` then make sure use SocialConnect : https://github.com/SocialConnect/auth avoid using this lib : oauth2-azure https://github.com/TheNetworg/oauth2-azure its buggy and you will get errors like `ERROR during authentication A01 NO AUTHENTICATE failed.`

You have stated, this lib is buggy, so I did not even consider it.

**Comment by darkworks** [comment]
> > @Orgoth Ok so this is for log purpose if you keep getting error : `ERROR during authentication A01 NO AUTHENTICATE failed.` then make sure use SocialConnect : https://github.com/SocialConnect/auth avoid using this lib : oauth2-azure https://github.com/TheNetworg/oauth2-azure its buggy and you will get errors like `ERROR during authentication A01 NO AUTHENTICATE failed.`
> 
> You have stated, this lib is buggy, so I did not even consider it.

oh my apologies i have edit my comment . ya i had issues with that lib and then after trying about 4 outh libs i came to conclusion that this lib was OK : https://github.com/TheNetworg/oauth2-azure 
it was just that scopes were not correct due to typo in Azur portal.
the social connect lib works ok with non-business emails it will not work with business emails. so install this lib ; https://github.com/TheNetworg/oauth2-azure

and then test. social connect i tested not work with business email however was ok with non business emails. and sorry for the trouble my comment had caused :(

**Comment by Orgoth** [comment]
> the social connect lib works ok with non-business emails it will not work with business emails. so install this lib ;

Yes, for business you need to create your own provider.  
The default provider by social connect can only call to https://login.live.com/oauth20_authorize.srf and https://login.live.com/oauth20_token.srf.  
For Business, you need to call https://login.microsoftonline.com/tenant/oauth2/v2.0/authorize and https://login.microsoftonline.com/common/v2.0/oauth2/token.  

I have created my own provider by extending the existing and applying the new URLs. :)  

I will try the lib by TheNetworg.

**Comment by darkworks** [comment]
> > the social connect lib works ok with non-business emails it will not work with business emails. so install this lib ;
> 
> Yes, for business you need to create your own provider. The default provider by social connect can only call to https://login.live.com/oauth20_authorize.srf and https://login.live.com/oauth20_token.srf. For Business, you need to call https://login.microsoftonline.com/tenant/oauth2/v2.0/authorize and https://login.microsoftonline.com/common/v2.0/oauth2/token.
> 
> I have created my own provider by extending the existing and applying the new URLs. :)
> 
> I will try the lib by TheNetworg.

ya i had made changes too like that
For Business, you need to call https://login.microsoftonline.com/tenant/oauth2/v2.0/authorize and https://login.microsoftonline.com/common/v2.0/oauth2/token.

but had no success with social connect

**Comment by Orgoth** [comment]
@darkworks  
Thank you very much for the help.  
With the lib from TheNetworg it has indeed worked for B2B.  

It would be really great if Microsoft would create a unified API here.

**Comment by adamhealthystuff** [comment]
> ding the existing and applying the

Could you share your azure auth script used for b2b?

I'm still getting the auth error using the above scopes with thenetworgs scripts.

**Comment by darkworks** [comment]
@adamhealthystuff you want to access business email or free user email ?

**Comment by darkworks** [comment]
> @darkworks Thank you very much for the help. With the lib from TheNetworg it has indeed worked for B2B.
> 
> It would be really great if Microsoft would create a unified API here.

ya its very annoying they have different end points for business and non business emails . very annoying it should be one api for both

**Comment by adamhealthystuff** [comment]
@darkworks Business email, I'm currently trying to use thenetworgs script with the following.

` $provider = new Azure([
        'clientId'          => $email_account->application_id,
        'clientSecret'      => $email_account->secret_value,
        'redirectUri'       => $email_account->redirect_uri,
        'tenant'            => $email_account->tenant_id,
        'approval_prompt' => 'auto',
        'scopes'    => [
            'offline_access',
            'https://outlook.office365.com/Mail.Read',
            'https://outlook.office365.com/profile',
            'https://outlook.office365.com/IMAP.AccessAsUser.All',
        ],
        'defaultEndPointVersion' => '2.0'
    ]);
`

**Comment by darkworks** [comment]
@adamhealthystuff  so what error it give to you ?

**Comment by adamhealthystuff** [comment]
> @adamhealthystuff so what error it give to you ?

Can not authenticate to IMAP server: A0001 NO AUTHENTICATE failed.

`$mailbox = imap2_open($server, $email_addr, $email_account->access_token, OP_XOAUTH2);`

**Comment by adamhealthystuff** [comment]
@darkworks 

Thanks for your help btw yeah here are the permissions

<img width="585" alt="image" src="https://user-images.githubusercontent.com/75440748/201097397-fd4cc2f1-42e6-4b2c-8361-f2a4a815f725.png">

**Comment by darkworks** [comment]
Hmmmm focus on Microsfot graph API permission instead of office 365 exchange online. 

you shared two screenshots and first screenshot have only 1 graph permission while 2nd have microsfot graph 4 permission . make sure you app have enough permission something like this 

![image](https://user-images.githubusercontent.com/12841788/201098494-d726d236-94d8-4550-b557-150be522a8d3.png)

**Comment by darkworks** [comment]
there is one another confusion in Azur portal so make sure your secret key is correct 

![image](https://user-images.githubusercontent.com/12841788/201098761-7e093512-3831-491e-a176-b5c45e7817af.png)
the secret key is actually the `Value` not the `Secret ID`

**Comment by adamhealthystuff** [comment]
I've updated this and ensured I'm using the secret value but I'm still getting the auth issue above.

Do I need to extract the token from the JWT or simply pass the whole value returned from `$access_token->getToken()`

<img width="491" alt="image" src="https://user-images.githubusercontent.com/75440748/201101084-f79f66d6-c8ec-413f-9204-88e804cc96d9.png">

**Comment by Orgoth** [comment]
@darkworks  
Getting the token and refreshtoken works now with B2B.  
But I now get the same error :)  

> A0001 NO AUTHENTICATE failed.

I am using the recommended scopes:
>        'offline_access',
>        'https://outlook.office365.com/profile',
>        'https://outlook.office365.com/Mail.ReadWrite',
>        'https://outlook.office365.com/IMAP.AccessAsUser.All',
>        'https://outlook.office365.com/SMTP.Send',

**Comment by darkworks** [comment]
@Orgoth  hmmmm do you have access to your primary b2b email and can you login to : https://admin.microsoft.com/Adminportal/Home
and send me screenshot so that i can guide you . you can hide users address in it. as it the moment i do not have access to admin account. from admin portal make sure the desire email is also authorized to use imap

**Comment by darkworks** [comment]
> @darkworks Getting the token and refreshtoken works now with B2B. But I now get the same error :)
> 
> > A0001 NO AUTHENTICATE failed.
> 
> I am using the recommended scopes:
> 
> > ```
> >    'offline_access',
> >    'https://outlook.office365.com/profile',
> >    'https://outlook.office365.com/Mail.ReadWrite',
> >    'https://outlook.office365.com/IMAP.AccessAsUser.All',
> >    'https://outlook.office365.com/SMTP.Send',
> > ```

so you getting `A0001 NO AUTHENTICATE failed.` error with refresh token only or also newly assigned token too

**Comment by Orgoth** [comment]
When I get back to work tomorrow, I'll send the screenshot.

**Comment by Orgoth** [comment]
> > @darkworks Getting the token and refreshtoken works now with B2B. But I now get the same error :)
> > > A0001 NO AUTHENTICATE failed.
> > 
> > 
> > I am using the recommended scopes:
> > > ```
> > >    'offline_access',
> > >    'https://outlook.office365.com/profile',
> > >    'https://outlook.office365.com/Mail.ReadWrite',
> > >    'https://outlook.office365.com/IMAP.AccessAsUser.All',
> > >    'https://outlook.office365.com/SMTP.Send',
> > > ```
> 
> so you getting `A0001 NO AUTHENTICATE failed.` error with refresh token only or also newly assigned token too

imap2_open with access token

**Comment by darkworks** [comment]
@Orgoth well access tokens are of two types one is fresh which you get by establishing fresh connection and another one is getting access token through refresh token. as when you get your first fresh token you will get refresh token with it. so u can save it to your session and then after hour when your access token expired then you can renew your access token through refresh token instead of requesting new fresh .

i refresh something like this, when their is about 5 min left in expire i renew it

```php
			if (isset($token)) {
				
				$now = time() + 300;
				if ($_SESSION["token_expires"] <= $now) {
				try {
				
					if (!is_null($_SESSION["refresh_token"])) {
					
						$token = $this->microsoft_outh->getAccessToken('refresh_token', [
						'scope' => $this->microsoft_outh->scope,
						'refresh_token' => $_SESSION["refresh_token"]
						]);
						
						$access_token = $this->update_token($token);
```	
```php
		public function update_token($token){
			$_SESSION['token_obj'] = $token;
			$_SESSION['access_token'] = $token->getToken();
			$_SESSION['refresh_token'] = $token->getRefreshToken();
			$_SESSION['token_expires'] = $token->getExpires();
			$this->access_token = $_SESSION['access_token'];
			return $_SESSION['access_token'];
		}
```

**Comment by Orgoth** [comment]
> @Orgoth well access tokens are of two types one is fresh which you get by establishing fresh connection and another one is getting access token through refresh token. as when you get your first fresh token you will get refresh token with it. so u can save it to your session and then after hour when your access token expired then you can renew your access token through refresh token instead of requesting new fresh .
> 
> i refresh something like this, when their is about 5 min left in expire i renew it
> 
> ```
> 			if (isset($token)) {
> 				
> 				$now = time() + 300;
> 				if ($_SESSION["token_expires"] <= $now) {
> 				try {
> 				
> 					if (!is_null($_SESSION["refresh_token"])) {
> 					
> 						$token = $this->microsoft_outh->getAccessToken('refresh_token', [
> 						'scope' => $this->microsoft_outh->scope,
> 						'refresh_token' => $_SESSION["refresh_token"]
> 						]);
> 						
> 						$access_token = $this->update_token($token);
> ```
> 
> ```
> 		public function update_token($token){
> 			$_SESSION['token_obj'] = $token;
> 			$_SESSION['access_token'] = $token->getToken();
> 			$_SESSION['refresh_token'] = $token->getRefreshToken();
> 			$_SESSION['token_expires'] = $token->getExpires();
> 			$this->access_token = $_SESSION['access_token'];
> 			return $_SESSION['access_token'];
> 		}
> ```

I know!  
I had also extended social connect, because it does not support refresh of tokens by itself!  
Private accounts work like a charm, only b2b does not.
I get the window for granting access and then the access and refresh token i save within a database, when the accesstoken ios about to expire i renew the token with the fresh token.

for social connect i use my self created class and for b2b i use the example of the repo it self, only that i supply the refresh token from my database

**Comment by Orgoth** [comment]
The system is structured in a centralized way, the systems that want to access something always ask oauth.einedomain.de first and get a new token and with this token they then ask the interfaces.
this ensures that the token is always up to date and has not expired.

**Comment by Orgoth** [comment]
> @Orgoth hmmmm do you have access to your primary b2b email and can you login to : https://admin.microsoft.com/Adminportal/Home and send me screenshot so that i can guide you . you can hide users address in it. as it the moment i do not have access to admin account. from admin portal make sure the desire email is also authorized to use imap

![Auswahl_328](https://user-images.githubusercontent.com/1035170/201289798-318fa271-0c23-4631-a1ac-ccc11fa52ec1.png)
