### ISSUE TITLE
Call to imap2_fetchstructure outputting debug

### ISSUE THREAD

**Issue by cjwnz** [javanile/php-imap2#9]
Getting output like example below when calling imap2_fetchstructure

`string(7) "related"
array(4) {
[0]=>
string(8) "boundary"
[1]=>
string(61) "_009_MEYP282MB1944C3591D84CE8BD3BB58AADFE90MEYP282MB1944AUSP_"
[2]=>
string(4) "type"
[3]=>
string(9) "text/html"
}
NULL
string(5) "en-US"`

**Comment by cjwnz** [comment]
Line #93 of BodyStructure.php

**Comment by francescobianco** [comment]
Hi @cjwnz , could you please test our new version https://github.com/javanile/php-imap2/releases/tag/0.1.9

**Comment by cjwnz** [comment]
Fixed thanks
